/*
 * This file is generated by jOOQ.
 */
package com.sljricardo.jooq.tables.references


import com.sljricardo.jooq.tables.Task
import com.sljricardo.jooq.tables.Users



/**
 * The table <code>TASK</code>.
 */
val TASK: Task = Task.TASK

/**
 * The table <code>USERS</code>.
 */
val USERS: Users = Users.USERS
